server:
  address: 0.0.0.0
  port: 8002

logging:
  level:
    co.zhanglintc.springcloudprovider.dao: debug

mybatis-plus:
  type-aliases-package: co.zhanglintc.springcloudapi.pojo
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

spring:
  application:
    name: spring-cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.56.101:3306/Spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    instance-id: given-provider-8002

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - "*"
  info:
    env:
      enabled: true

info:
  app.name: provider-8002
  any.thing: anything
