server:
  address: 0.0.0.0
  port: 7002

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: given-eureka-center-7002
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka
