server:
  address: 0.0.0.0
  port: 9002

spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
