server:
  address: 0.0.0.0
  port: 3355

spring:
  application:
    name: spring-cloud-config-local-client

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"