server:
  address: 0.0.0.0
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhanglintc/ohMyConfigRepo.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    instance-id: given-cloud-config-server-3344

info:
  app.name: cloud-config-server-3344
  any.thing: anything
  type: server
