server:
  address: 0.0.0.0
  port: 7001

eureka:
  instance:
    hostname: center
    instance-id: given-eureka-center
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka
