server:
  address: 0.0.0.0
  port: 9527

mybatis-plus:
  type-aliases-package: co.zhanglintc.springcloudapi.pojo
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

spring:
  application:
    name: spring-cloud-provider-zuul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.56.101:3306/Spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    instance-id: given-provider-zuul-9527

zuul:
  routes:
    provider.serviceId: spring-cloud-provider
    provider.path: /provider/**
  ignored-services:
    - spring-cloud-provider
    - "*"
  prefix: /cloud

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - "*"
  info:
    env:
      enabled: true

info:
  app.name: provider-zuul-9527
  any.thing: anything
  url.ignored: http://localhost:9527/cloud/spring-cloud-provider
  url.current: http://localhost:9527/cloud/provider
  url.notice: "Zuul not compatible with 'spring-cloud-dependencies-version-2021.0.2' and 'spring-boot-dependencies-version-2.6.7' anymore"

